#write aprogram to display big letter T
print("=========================")
print("=========================")
print("=========================")
print("=========================")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")
print("             ||          ")