f_name=input("What is your name?")
print("My first name is",f_name)
s_name=input("What is your second name?")
print("My second name is",s_name)
f_num=input("enter first number:")
s_num=input("enter second number")
#convert string into integers
sum_num=int(f_num) + int(s_num)
print("the sum of numbers",sum_num)
pro_num=int(f_num) * int(s_num)
print("The product of numbers is",pro_num)
diff_num=int(f_num) - int(s_num)
print("The difference of numbers is",diff_num)
quo_num=int(f_num) / int(s_num)
print("The quotient of the numbers is",quo_num)